import AppLayout from '@/components/layout/app-layout';
// import './global.css';
import "@/styles/globals.css";

export const metadata = {
  title: 'Welcome to urs-web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className='dark-mode'>
      <body>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
