import './global.css';

export const metadata = {
  title: 'Welcome to urs-web',
  description: 'Generated by create-nx-workspace',
};

import { Provider } from "@/components/ui/provider"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
